name: CI

on:
  push:
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install
      - name: Run flake8
        run: |
          poetry run flake8 modbusbackup.py
      - name: Check imports
        run: |
          poetry run isort -c modbusbackup.py
      - name: Check black
        run: |
          poetry run black --check modbusbackup.py
